### ISSUE TITLE
Add support for Process.close() method (added in CPython 3.7)

### ISSUE THREAD

**Issue by millerdev** [jgehrcke/gipc#90]
gipc processes started with `proc = start_process(...)` always error on `proc.close()`:

`ValueError: Cannot close a process while it is still running. You should first call join() or terminate().`

The problem is that `_GProcess` patches `_popen.poll` to return `None`:

https://github.com/jgehrcke/gipc/blob/e79845d6af4f6c574eb344b1c7d3aa2c421d255b/gipc/gipc.py#L448

This breaks the implementation of `multiprocessing.Process.close`, which [raises an error if `_popen.poll()` returns `None`](https://github.com/python/cpython/blob/b24e4fac03409c4f845758d7ed884c5a99368493/Lib/multiprocessing/process.py#L180-L182).

**Comment by jgehrcke** [comment]
Thank you for reporting this. Which Python version did you use to run into this? CPython 3.8, on Linux?

**Comment by millerdev** [comment]
3.7 on macOS. The [`close()` method](https://docs.python.org/3.7/library/multiprocessing.html#multiprocessing.Process.close) was added in 3.7

**Comment by jgehrcke** [comment]
Gotcha, thanks, I'll look into that!

**Comment by jgehrcke** [comment]
I felt free to rename this issue. Did a bit of CI maintenance work (https://github.com/jgehrcke/gipc/pull/91) that will allow for confidently adding support for the `close()` method to gipc.

We cannot call the original `.close()` method, as outlined in the gipc code base, because that will invoke a wait()-like system call -- which would conflict with the libev child watcher's mechanism.

My plan is, I think, to provide a close() implementation very close to what the original does.

**Comment by jgehrcke** [comment]
Working on this in https://github.com/jgehrcke/gipc/pull/93

**Comment by jgehrcke** [comment]
@millerdev I just released gipc 1.1.0 which should resolve this. If you can, please give it a quick test! Thank you!
